name: Documentation Updates

on:
  push:
    branches:
      - master
    paths:
      - "src/defaultsettings.yml"

env:
  WAPI: https://werewolf.chat/w/api.php
  WPAGE: Configuration
  WUSER: ${{ secrets.WIKI_USERNAME }}
  WPASS: ${{ secrets.WIKI_PASSWORD }}

jobs:
  config:
    name: Configuration Page
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update Configuration Page
        run: python gendoc.py "$WAPI" "$WUSER" "$WPASS" "$WPAGE" "$GITHUB_SHA"
