name: Documentation Updates

on:
  push:
    branches:
      - master
    paths:
      - "src/defaultsettings.yml"
      - "src/roles/**"
      - "src/gamemodes/**"
      - "gendoc.py"
  workflow_dispatch:

env:
  WAPI: https://werewolf.chat/w/api.php
  WUSER: ${{ secrets.WIKI_USERNAME }}
  WPASS: ${{ secrets.WIKI_PASSWORD }}

jobs:
  wiki:
    name: Update Wiki
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update Wiki Pages
        run: python gendoc.py "$WAPI" "$WUSER" "$WPASS" "$GITHUB_SHA"
